# Generated by Django 4.1 on 2022-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=40)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
