# Generated by Django 4.1 on 2022-09-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40),
        ),
    ]
